name: Build Fabric mod

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.6"

      - name: Build
        working-directory: CrouchLock
        run: gradle build --stacktrace

      - uses: actions/upload-artifact@v4
        with:
          name: crouchlock-1.1.1
          path: CrouchLock/build/libs/crouchlock-*.jar
          if-no-files-found: error
